### ISSUE TITLE
EPG XML does not have a closing tag </tv>

### ISSUE THREAD

**Issue by plimut** [vstavrinov/acestream_search#4]
Hello, there is a problem when getting the EPG in the request http://localhost:8000/search.m3u?xml_epg=1

```
<?xml version="1.0" encoding="utf-8" ?>
<tv>
  <channel id="261997">
    <display-name lang="ru">Setanta Live 1 [RU]</display-name>
  </channel>
  <programme start="20230525220000 +0300" stop="20230526000000 +0300" channel="261997">
    <title lang="ru">Футбол. Чемпионат Англии. Премьер-лига. Брайтон энд Хоув Альбион - Манчестер Сити. Прямая трансляция.</title>
  </programme>
```
I couldn't find the EPG shaper. The request can be terminated without the closing `</tv>` tag, the data is not usable.

**Comment by vstavrinov** [comment]
There are no such problem if You will use query option e.g. 

`acestream_search --xml_epg BCU`

Need further study.

**Comment by vstavrinov** [comment]
Fixed. 

It is rather an acestream engine bug than mine. This is the type issue for certain data.  The problem was that acestream engine returns json where channel name, comprising digits only, represented as int type but xml expects string type.

Don't forget to update container image. Thank You for Your report.
